/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 whatsapp.gltf 
Author: AlbertVictory (https://sketchfab.com/albert_victory)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/whatsapp-3d-logo-e51c67d110014bcdb71adf678f1bfc81
Title: WhatsApp 3D-logo
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/whatsapp.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.029, -0.028]} rotation={[-2.884, 0, -Math.PI / 2]} scale={[1, 0.092, 1]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.002']} position={[0.303, 0.625, 0.072]} rotation={[-Math.PI, 0.257, -Math.PI]} scale={[1, 10.861, 1]} />
      </group>
    </group>
  )
}

useGLTF.preload('/whatsapp.gltf')
